### PR TITLE
Display sample videos in information tab (kind of)

### PR DESCRIPTION
**Pull request by hiddefolkertsma**

### CODE REVIEW

**Comment by hiddefolkertsma** [comment]
Fixes #19.

**Comment by hiddefolkertsma** [comment]
The Xcode settings updates are necessary to make the url_launcher plugin work on iOS. The workaround is described here: https://groups.google.com/d/msg/flutter-dev/7QRk1RphLDE/5rLS4CciBwAJ

**Comment by juliusvdijk** [comment]
I have the following error in 'information_tab_page.dart': `The name 'InfoEntryItem' is defined in the libraries 'faq_tab_page.dart' and 'information_tab_page.dart`

I think you could prepend the InfoEntryItem by an _ to make them private or you if they are the same then they should be merged.

**Comment by hiddefolkertsma** [comment]
Ah yes, I forgot about that and didn’t add `faq_tab_page.dart` to any commits. I renamed `InfoEntryItem` to something along the lines of `FAQEntryItem` there. Will fix tomorrow.

**Comment by hiddefolkertsma** [comment]
"Tomorrow" 🤫

**Review by ndrong — CHANGES_REQUESTED** [review]
Looks good!
A few notes to make it perfect:
- Use the `CupertinoPageRoute` rather than the `MaterialPageRoute` for consistency.
- Make sure the `Scaffold` matches the other `Scaffold`s in the app.

**Review by ndrong — APPROVED** [review]

**Pull request merged**
