### PR TITLE
First working version

### PR DESCRIPTION
**Pull request by ndrong**
This version contains four tabs and (empty) views.

### CODE REVIEW

**Review by hiddefolkertsma — COMMENTED** [review]
Why just "app"?

**Comment by ndrong** [comment]
I figured the app name would be redundant, as well as the platform, given the name of this repo. :P

**Comment by ndrong** [comment]
Plus, technically an Android version is contained as well.

**Comment by hiddefolkertsma** [comment]
True. Might want to just call it "Tuberculosis" for now, as grim as that sounds. I don't like just naming it "app".

**Comment by ndrong** [comment]
There you go ;)

**Review by hiddefolkertsma — APPROVED** [review]

**Pull request merged**
